[General]
network = DMV_Advanced
cpu-time-limit = 60s

# Here we have our 3 clerks
*.numClerks = 3
*.arrival.interArrivalTime = exponential(2s)
*.clerk[*].serviceTime = exponential(5s)

# Here we are recording the data
**.waitTime.result-recording-modes = +vector
**.queueLen.result-recording-modes = +vector

*.licenseClerk[*].serviceTime = exponential(10s) # Licenses take longer
*.regClerk[*].serviceTime = exponential(5s)    # Registrations are faster